# Generated by Django 2.1.2 on 2018-10-10 14:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import elementary.apps
import elementary.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=254, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_robot', models.BooleanField(default=False, verbose_name='Robot')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Firstname')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Lastname')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('update_by', models.CharField(editable=False, max_length=254, verbose_name='Update by')),
                ('method', models.CharField(choices=[('CREATESUPERUSER', 'Create Super User'), ('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end'), ('ADDITIONAL', 'Additional method')], default='BACKEND', max_length=15, verbose_name='Create method')),
                ('key', models.CharField(default=elementary.apps.ElementaryConfig.key, max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
                'permissions': (('can_use_api', 'Can use API'), ('can_csrf_exempt', 'Can csrf exempt'), ('can_read_user', 'Can detail and list user'), ('can_see_email', 'Can see email'), ('can_see_firstname', 'Can see firstname'), ('can_see_lastname', 'Can see lastname'), ('can_see_method', 'Can see method'), ('can_see_groups', 'Can see groups'), ('can_see_permissions', 'Can see permissions'), ('can_see_additional', 'Can see additional'), ('can_see_key', 'Can see key')),
            },
            managers=[
                ('objects', elementary.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('update_by', models.CharField(blank=True, editable=False, help_text='Last user who modified.', max_length=254, null=True, verbose_name='Update by')),
                ('error', models.TextField(blank=True, help_text='Detail about the error.', null=True, verbose_name='Error encountered')),
                ('info', models.TextField(blank=True, help_text='add additional information', null=True, verbose_name='Additional information')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
            bases=('auth.group', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('update_by', models.CharField(blank=True, editable=False, help_text='Last user who modified.', max_length=254, null=True, verbose_name='Update by')),
                ('error', models.TextField(blank=True, help_text='Detail about the error.', null=True, verbose_name='Error encountered')),
                ('info', models.TextField(blank=True, help_text='add additional information', null=True, verbose_name='Additional information')),
                ('method', models.CharField(help_text='Method type', max_length=4, verbose_name='Create method')),
                ('name', models.CharField(help_text='Method name', max_length=254, verbose_name='Name')),
                ('enable', models.BooleanField(default=True, help_text='Enable or disable the method', verbose_name='Enable')),
                ('port', models.PositiveIntegerField(blank=True, default=0, help_text='Change the port used by the method', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Port')),
                ('tls', models.BooleanField(default=False, help_text='Enable or disable TLS', verbose_name='Enable TLS')),
                ('certificate', models.TextField(blank=True, help_text='Uploaded here the certificate to check', null=True, verbose_name='TLS Certificate')),
                ('self_signed', models.BooleanField(default=False, help_text='Is the certificate self-signed?', verbose_name='Self-signed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Will be superuser')),
                ('field_firstname', models.CharField(blank=True, help_text='Automatically filled field with key map (Keep null if not used)', max_length=254, null=True, verbose_name='Firstname correspondence')),
                ('field_lastname', models.CharField(blank=True, help_text='Automatically filled field with key map (Keep null if not used)', max_length=254, null=True, verbose_name='Lastname correspondence')),
                ('field_email', models.CharField(blank=True, help_text='Automatically filled field with key map (Keep null if not used)', max_length=254, null=True, verbose_name='Email correspondence')),
                ('groups', models.ManyToManyField(blank=True, to='elementary.Group', verbose_name='Groups associated')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Permissions associated')),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Methods',
                'permissions': (('can_read_method', 'Can detail and list method'), ('can_check_method', 'Can check method'), ('can_writecert_method', 'Can write certificate method')),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='additional',
            field=models.ManyToManyField(blank=True, to='elementary.Method'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
